# Generated by Django 2.2 on 2020-05-26 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('select_time', models.DateTimeField(blank=True, null=True)),
                ('project_completed', models.BooleanField(default=False)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebHookSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('webhook_event', models.CharField(blank=True, choices=[('on_test_complete', 'Test Complete'), ('on_report_ready', 'Report Ready')], default='test_complete', max_length=140, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', editable=False, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Enterprise')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseDeveloperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_base', models.URLField(blank=True, null=True)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('competency', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('grading', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('report_ready', models.BooleanField(default=False)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.EnterpriseDeveloper')),
            ],
        ),
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='api.EnterpriseProject'),
        ),
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='temp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.IdeTemporalUser'),
        ),
        migrations.CreateModel(
            name='EnterpriseAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.Enterprise')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
