# Generated by Django 2.2 on 2020-05-26 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('job_role', models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend  Developer', 'Backend  Developer'), ('Android  Developer', 'Android  Developer'), ('Graphic Designer', 'Graphic Designer'), ('IOS Developer', 'IOS Developer'), ('Data Scientist', 'Data Scientist')], default='Full Stack Developer', max_length=30)),
                ('dev_experience', models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='Mid-Level', max_length=30)),
                ('engagement_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], default='Full-time', max_length=30)),
                ('tech_stack', models.CharField(max_length=500)),
                ('num_devs_wanted', models.IntegerField(default=1)),
                ('location', django_countries.fields.CountryField(max_length=2, null=True)),
                ('remuneration', models.CharField(help_text='in dollars ($)', max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position_filled', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('stage', models.CharField(max_length=500, null=True)),
                ('interviewstarttime', models.DateTimeField(blank=True, null=True)),
                ('interviewendtime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(max_length=1500, null=True)),
                ('test_stage', models.CharField(max_length=500, null=True)),
                ('report', models.CharField(max_length=500, null=True)),
                ('interviewstatus', models.CharField(max_length=500, null=True)),
                ('eventcolor', models.CharField(default='blue', max_length=100, null=True)),
                ('projectstarttime', models.DateTimeField(blank=True, null=True)),
                ('offerstatus', models.CharField(max_length=500, null=True)),
                ('offerletter', models.CharField(max_length=500, null=True)),
                ('demolink', models.CharField(blank=True, max_length=100, null=True)),
                ('carted', models.BooleanField(default=False)),
                ('type', models.CharField(default='applied', max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('framework', models.CharField(max_length=500, null=True)),
                ('teststarttime', models.DateTimeField(blank=True, null=True)),
                ('testendtime', models.DateTimeField(blank=True, null=True)),
                ('rejectionreason', models.CharField(blank=True, max_length=1500, null=True)),
                ('rejectioncomment', models.CharField(blank=True, max_length=1500, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devs', to='accounts.Profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='marketplace.Job')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobrecruiter', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DevRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('stage', models.CharField(max_length=500, null=True)),
                ('interviewstarttime', models.DateTimeField(blank=True, null=True)),
                ('interviewendtime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(max_length=1500, null=True)),
                ('test_stage', models.CharField(max_length=500, null=True)),
                ('report', models.CharField(max_length=500, null=True)),
                ('interviewstatus', models.CharField(max_length=500, null=True)),
                ('eventcolor', models.CharField(default='blue', max_length=100, null=True)),
                ('projectstarttime', models.DateTimeField(blank=True, null=True)),
                ('offerstatus', models.CharField(max_length=500, null=True)),
                ('offerletter', models.CharField(max_length=500, null=True)),
                ('demolink', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devaccount', to='accounts.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Profile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
