# Generated by Django 2.2 on 2020-05-26 21:43

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import separatedvaluesfield.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('recruiter', 'RECRUITER'), ('developer', 'DEVELOPER')], max_length=30, null=True)),
                ('stage', models.CharField(choices=[('profile_type_selection', 'profile_type_selection'), ('recuiter_filling_details', 'recuiter_filling_details'), ('developer_filling_details', 'developer_filling_details'), ('complete', 'complete')], default='profile_type_selection', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('csa', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('student', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('linkedin_url', models.CharField(max_length=500, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=500, null=True)),
                ('github_repo', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=140, null=True)),
                ('framework', models.CharField(blank=True, max_length=140, null=True)),
                ('years', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-4', '2-4'), ('4-above', '4-above')], max_length=30, null=True)),
                ('about', models.CharField(max_length=300, null=True)),
                ('profile_tags', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('skills', models.CharField(blank=True, max_length=900, null=True)),
                ('verified_skills', models.CharField(blank=True, max_length=900, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('availabilty', models.CharField(blank=True, max_length=100, null=True)),
                ('notifications', models.BooleanField(default=True)),
                ('remote_entry', models.BooleanField(default=False)),
                ('remote_verified', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=140, null=True)),
                ('job_role', models.CharField(blank=True, max_length=140, null=True)),
                ('industry', models.CharField(blank=True, max_length=80, null=True)),
                ('company_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('salary', models.IntegerField(null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default='', editable=False, null=True, unique=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IdeTemporalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferers', to='accounts.Profile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reffereds', to='accounts.Profile')),
            ],
            options={
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
