# Generated by Django 2.2 on 2020-05-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import separatedvaluesfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        ('classroom', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('discord', models.CharField(max_length=300, null=True)),
                ('members', models.CharField(max_length=800, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=300, null=True)),
                ('likes', models.CharField(blank=True, max_length=900, null=True)),
                ('dislikes', models.CharField(blank=True, max_length=900, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('keycompitency', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('grading', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('score', models.IntegerField(null=True)),
                ('github', models.CharField(max_length=300, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('repository_link', models.CharField(max_length=400, null=True)),
                ('demo_link', models.CharField(max_length=400, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('tech_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('csa', models.BooleanField(default=False)),
                ('likes', models.CharField(blank=True, max_length=900, null=True)),
                ('dislikes', models.CharField(blank=True, max_length=900, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateportfolio', to='accounts.Profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('location', django_countries.fields.CountryField(max_length=2, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateexperience', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='candidatesprojects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('awaiting_candidate', 'Awaiting Candidate'), ('invite_accepted', 'Invite Accepted'), ('time_set', 'Time Set'), ('link_available', 'Link Available'), ('in_progress', 'In Progress'), ('project_completed', 'Project Completed'), ('analysis_started', 'Analysis Started'), ('transfer_complete', 'Transfer Complete'), ('analysis_complete', 'Analysis Complete')], default='awaiting_candidate', max_length=100)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('invite_accepted', 'Invite Accepted'), ('time_set', 'Time Set'), ('link_available', 'Link Available'), ('in_progress', 'In Progress'), ('project_completed', 'Project Completed'), ('analysis_started', 'Analysis Started'), ('transfer_complete', 'Transfer Complete'), ('analysis_complete', 'Analysis Complete')], default='invite_accepted', max_length=100, null=True)),
                ('test_choice', models.CharField(choices=[('on_site_test', 'On Site Test'), ('automated_test', 'Automated Test')], default='automated_test', max_length=100)),
                ('report', models.CharField(max_length=500, null=True)),
                ('projectstarttime', models.DateTimeField(blank=True, null=True)),
                ('frameworktested', models.CharField(blank=True, max_length=500, null=True)),
                ('demolink', models.CharField(blank=True, max_length=100, null=True)),
                ('csa', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('test_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.TestCenter')),
            ],
        ),
    ]
